### ISSUE TITLE
Applying updates of 27/10/2016 for RHEL 6 is not possible due to dependencies

### ISSUE THREAD

**Issue by srrbvdwl** [globus/globus-toolkit#79]
When running the update I'm seeing:
Resolving Dependencies
--> Running transaction check
---> Package globus-authz.x86_64 0:3.12-1.el6+gt6 will be updated
---> Package globus-authz.x86_64 0:3.15-1.el6+gt6 will be an update
---> Package globus-authz-callout-error.x86_64 0:3.5-2.el6+gt6 will be updated
---> Package globus-authz-callout-error.x86_64 0:3.6-3.el6+gt6 will be an update
---> Package globus-callout.x86_64 0:3.14-1.el6+gt6 will be updated
---> Package globus-callout.x86_64 0:3.15-3.el6+gt6 will be an update
---> Package globus-common.x86_64 0:16.5-1.el6+gt6 will be updated
---> Package globus-common.x86_64 0:16.8-2.el6+gt6 will be an update
---> Package globus-common-devel.x86_64 0:16.5-1.el6+gt6 will be updated
---> Package globus-common-devel.x86_64 0:16.8-2.el6+gt6 will be an update
---> Package globus-common-progs.x86_64 0:16.5-1.el6+gt6 will be updated
---> Package globus-common-progs.x86_64 0:16.8-2.el6+gt6 will be an update
---> Package globus-ftp-client.x86_64 0:8.29-1.el6+gt6 will be updated
---> Package globus-ftp-client.x86_64 0:8.33-1.el6+gt6 will be an update
---> Package globus-ftp-control.x86_64 0:7.7-1.el6+gt6 will be updated
---> Package globus-ftp-control.x86_64 0:7.7-2.el6+gt6 will be an update
---> Package globus-gass-cache.x86_64 0:9.8-1.el6+gt6 will be updated
---> Package globus-gass-cache.x86_64 0:9.10-1.el6+gt6 will be an update
---> Package globus-gass-cache-program.x86_64 0:6.5-2.el6+gt6 will be updated
---> Package globus-gass-cache-program.x86_64 0:6.6-3.el6+gt6 will be an update
---> Package globus-gass-copy.x86_64 0:9.19-1.el6+gt6 will be updated
---> Package globus-gass-copy.x86_64 0:9.23-1.el6+gt6 will be an update
---> Package globus-gass-copy-progs.x86_64 0:9.19-1.el6+gt6 will be updated
---> Package globus-gass-copy-progs.x86_64 0:9.23-1.el6+gt6 will be an update
---> Package globus-gass-server-ez.x86_64 0:5.7-2.el6+gt6 will be updated
---> Package globus-gass-server-ez.x86_64 0:5.8-3.el6+gt6 will be an update
---> Package globus-gass-server-ez-progs.x86_64 0:5.7-2.el6+gt6 will be updated
---> Package globus-gass-server-ez-progs.x86_64 0:5.8-3.el6+gt6 will be an update
---> Package globus-gass-transfer.x86_64 0:8.9-1.el6+gt6 will be updated
---> Package globus-gass-transfer.x86_64 0:8.10-3.el6+gt6 will be an update
---> Package globus-gatekeeper.x86_64 0:10.10-2.el6+gt6 will be updated
---> Package globus-gatekeeper.x86_64 0:10.12-1.el6+gt6 will be an update
---> Package globus-gfork.x86_64 0:4.8-2.el6+gt6 will be updated
---> Package globus-gfork.x86_64 0:4.9-4.el6+gt6 will be an update
---> Package globus-gfork-progs.x86_64 0:4.8-2.el6+gt6 will be updated
---> Package globus-gfork-progs.x86_64 0:4.9-4.el6+gt6 will be an update
---> Package globus-gram-client.x86_64 0:13.13-1.el6+gt6 will be updated
---> Package globus-gram-client.x86_64 0:13.16-1.el6+gt6 will be an update
---> Package globus-gram-client-tools.x86_64 0:11.8-1.el6+gt6 will be updated
---> Package globus-gram-client-tools.x86_64 0:11.10-1.el6+gt6 will be an update
---> Package globus-gram-job-manager.x86_64 0:14.27-3.el6+gt6 will be updated
---> Package globus-gram-job-manager.x86_64 0:14.35-1.el6+gt6 will be an update
---> Package globus-gram-job-manager-callout-error.x86_64 0:3.5-2.el6+gt6 will be updated
---> Package globus-gram-job-manager-callout-error.x86_64 0:3.6-3.el6+gt6 will be an update
---> Package globus-gram-job-manager-fork.x86_64 0:2.4-2.el6+gt6 will be updated
---> Package globus-gram-job-manager-fork.x86_64 0:2.6-1.el6+gt6 will be an update
---> Package globus-gram-job-manager-fork-setup-poll.noarch 0:2.4-2.el6+gt6 will be updated
---> Package globus-gram-job-manager-fork-setup-poll.noarch 0:2.6-1.el6+gt6 will be an update
---> Package globus-gram-job-manager-scripts.noarch 0:6.7-2.el6+gt6 will be updated
---> Package globus-gram-job-manager-scripts.noarch 0:6.9-1.el6+gt6 will be an update
---> Package globus-gram-job-manager-slurm.noarch 0:2.7-2.el6+gt6 will be updated
---> Package globus-gram-job-manager-slurm.noarch 0:2.8-3.el6+gt6 will be an update
---> Package globus-gram-job-manager-slurm-setup-poll.noarch 0:2.7-2.el6+gt6 will be updated
---> Package globus-gram-job-manager-slurm-setup-poll.noarch 0:2.8-3.el6+gt6 will be an update
---> Package globus-gram-protocol.x86_64 0:12.12-2.el6+gt6 will be updated
---> Package globus-gram-protocol.x86_64 0:12.15-1.el6+gt6 will be an update
---> Package globus-gridftp-server.x86_64 0:11.1-1.el6+gt6 will be updated
---> Package globus-gridftp-server.x86_64 0:11.7-1.el6+gt6 will be an update
---> Package globus-gridftp-server-control.x86_64 0:4.1-1.el6+gt6 will be updated
---> Package globus-gridftp-server-control.x86_64 0:4.2-4.el6+gt6 will be an update
---> Package globus-gridftp-server-progs.x86_64 0:11.1-1.el6+gt6 will be updated
---> Package globus-gridftp-server-progs.x86_64 0:11.7-1.el6+gt6 will be an update
---> Package globus-gsi-callback.x86_64 0:5.8-2.el6+gt6 will be updated
---> Package globus-gsi-callback.x86_64 0:5.12-1.el6+gt6 will be an update
---> Package globus-gsi-cert-utils.x86_64 0:9.12-1.el6+gt6 will be updated
---> Package globus-gsi-cert-utils.x86_64 0:9.15-1.el6+gt6 will be an update
---> Package globus-gsi-cert-utils-progs.x86_64 0:9.12-1.el6+gt6 will be updated
---> Package globus-gsi-cert-utils-progs.x86_64 0:9.15-1.el6+gt6 will be an update
---> Package globus-gsi-credential.x86_64 0:7.9-2.el6+gt6 will be updated
---> Package globus-gsi-credential.x86_64 0:7.11-1.el6+gt6 will be an update
---> Package globus-gsi-openssl-error.x86_64 0:3.5-2.el6+gt6 will be updated
---> Package globus-gsi-openssl-error.x86_64 0:3.7-1.el6+gt6 will be an update
---> Package globus-gsi-proxy-core.x86_64 0:7.9-1.el6+gt6 will be updated
---> Package globus-gsi-proxy-core.x86_64 0:8.6-1.el6+gt6 will be an update
---> Package globus-gsi-proxy-ssl.x86_64 0:5.8-1.el6+gt6 will be updated
---> Package globus-gsi-proxy-ssl.x86_64 0:5.10-1.el6+gt6 will be an update
---> Package globus-gsi-sysconfig.x86_64 0:6.9-1.el6+gt6 will be updated
---> Package globus-gsi-sysconfig.x86_64 0:6.11-1.el6+gt6 will be an update
---> Package globus-gss-assist.x86_64 0:10.15-2.el6+gt6 will be updated
---> Package globus-gss-assist.x86_64 0:10.20-1.el6+gt6 will be an update
---> Package globus-gss-assist-progs.x86_64 0:10.15-2.el6+gt6 will be updated
---> Package globus-gss-assist-progs.x86_64 0:10.20-1.el6+gt6 will be an update
---> Package globus-gssapi-error.x86_64 0:5.4-2.el6+gt6 will be updated
---> Package globus-gssapi-error.x86_64 0:5.5-3.el6+gt6 will be an update
---> Package globus-gssapi-gsi.x86_64 0:12.1-1.el6+gt6 will be updated
---> Package globus-gssapi-gsi.x86_64 0:12.11-1.el6+gt6 will be an update
---> Package globus-io.x86_64 0:11.5-1.el6+gt6 will be updated
---> Package globus-io.x86_64 0:11.8-1.el6+gt6 will be an update
---> Package globus-openssl-module.x86_64 0:4.6-2.el6+gt6 will be updated
---> Package globus-openssl-module.x86_64 0:4.8-1.el6+gt6 will be an update
---> Package globus-proxy-utils.x86_64 0:6.15-1.el6+gt6 will be updated
---> Package globus-proxy-utils.x86_64 0:6.18-1.el6+gt6 will be an update
---> Package globus-rsl.x86_64 0:10.10-2.el6+gt6 will be updated
---> Package globus-rsl.x86_64 0:10.11-4.el6+gt6 will be an update
---> Package globus-scheduler-event-generator.x86_64 0:5.11-2.el6+gt6 will be updated
---> Package globus-scheduler-event-generator.x86_64 0:5.12-5.el6+gt6 will be an update
---> Package globus-simple-ca.noarch 0:4.22-2.el6+gt6 will be updated
---> Package globus-simple-ca.noarch 0:4.24-3.el6+gt6 will be an update
---> Package globus-usage.x86_64 0:4.4-2.el6+gt6 will be updated
---> Package globus-usage.x86_64 0:4.5-3.el6+gt6 will be an update
---> Package globus-xio.x86_64 0:5.12-1.el6+gt6 will be updated
---> Package globus-xio.x86_64 0:5.13-4.el6+gt6 will be an update
---> Package globus-xio-gsi-driver.x86_64 0:3.10-1.el6+gt6 will be updated
---> Package globus-xio-gsi-driver.x86_64 0:3.10-3.el6+gt6 will be an update
---> Package globus-xio-pipe-driver.x86_64 0:3.8-1.el6+gt6 will be updated
---> Package globus-xio-pipe-driver.x86_64 0:3.9-3.el6+gt6 will be an update
---> Package globus-xio-popen-driver.x86_64 0:3.5-2.el6+gt6 will be updated
---> Package globus-xio-popen-driver.x86_64 0:3.6-3.el6+gt6 will be an update
---> Package globus-xio-udt-driver.x86_64 0:1.23-3.el6+gt6 will be updated
---> Package globus-xio-udt-driver.x86_64 0:1.25-1.el6+gt6 will be an update
--> Processing Dependency: libudt.so.0()(64bit) for package: globus-xio-udt-driver-1.25-1.el6+gt6.x86_64
---> Package globus-xioperf.x86_64 0:4.4-2.el6+gt6 will be updated
---> Package globus-xioperf.x86_64 0:4.5-3.el6+gt6 will be an update
---> Package gsi-openssh.x86_64 0:7.1p2f-1.el6+gt6 will be updated
---> Package gsi-openssh.x86_64 0:7.1p2f-4.el6+gt6 will be an update
---> Package gsi-openssh-clients.x86_64 0:7.1p2f-1.el6+gt6 will be updated
---> Package gsi-openssh-clients.x86_64 0:7.1p2f-4.el6+gt6 will be an update
---> Package gsi-openssh-server.x86_64 0:7.1p2f-1.el6+gt6 will be updated
---> Package gsi-openssh-server.x86_64 0:7.1p2f-4.el6+gt6 will be an update
---> Package myproxy.x86_64 0:6.1.18-1.el6+gt6 will be updated
---> Package myproxy.x86_64 0:6.1.21-1.el6+gt6 will be an update
--> Processing Dependency: libs = 6.1.21-1.el6+gt6 for package: myproxy-6.1.21-1.el6+gt6.x86_64
---> Package myproxy-admin.x86_64 0:6.1.18-1.el6+gt6 will be updated
---> Package myproxy-admin.x86_64 0:6.1.21-1.el6+gt6 will be an update
--> Processing Dependency: libs = 6.1.21-1.el6+gt6 for package: myproxy-admin-6.1.21-1.el6+gt6.x86_64
---> Package myproxy-libs.x86_64 0:6.1.18-1.el6+gt6 will be updated
---> Package myproxy-libs.x86_64 0:6.1.21-1.el6+gt6 will be an update
---> Package myproxy-server.x86_64 0:6.1.18-1.el6+gt6 will be updated
---> Package myproxy-server.x86_64 0:6.1.21-1.el6+gt6 will be an update
--> Processing Dependency: libs = 6.1.21-1.el6+gt6 for package: myproxy-server-6.1.21-1.el6+gt6.x86_64
--> Finished Dependency Resolution
Error: Package: myproxy-server-6.1.21-1.el6+gt6.x86_64 (local_Globus-Toolkit-6-el6)
           Requires: libs = 6.1.21-1.el6+gt6
Error: Package: myproxy-admin-6.1.21-1.el6+gt6.x86_64 (local_Globus-Toolkit-6-el6)
           Requires: libs = 6.1.21-1.el6+gt6
Error: Package: globus-xio-udt-driver-1.25-1.el6+gt6.x86_64 (local_Globus-Toolkit-6-el6)
           Requires: libudt.so.0()(64bit)
Error: Package: myproxy-6.1.21-1.el6+gt6.x86_64 (local_Globus-Toolkit-6-el6)
           Requires: libs = 6.1.21-1.el6+gt6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Imho the requirement for myproxy should be myproxy-libs and the requirement for globus-xio-udt-driver.x86_64 used to be libudt.so()(64bit) and not libudt.so.1.

**Comment by bester** [comment]
I've published a new package to address this issue.

**Comment by srrbvdwl** [comment]
Thanks, but I still get the following:
Error: Package: globus-xio-udt-driver-1.25-1.el6+gt6.x86_64 (local_Globus-Toolkit-6-el6)
           Requires: libudt.so.0()(64bit)

**Comment by bester** [comment]
Are you using the udt package from EPEL or something else?

Joe

**Comment by srrbvdwl** [comment]
Hi,

No just from the globus toolkit repository from "http://www.globus.org/ftppub/gt6/stable/rpm/el/6/$basearch/"

I'm  trying to update globus-xio-udt-driver-1.23-3.el6+gt6.x86_64 which is certainly not in the epel repository.

**Comment by bester** [comment]
I've removed those packages from our repository, since epel includes those and we require epel for some other parts of the globus-connect-server stack
